version: '3.8'

services:
  localstack:
    image: localstack/localstack:stable
    
    ports:
      - "4566:4566"            # LocalStack Edge Proxy
      - "4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=sqs,s3
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"  # Prometheus port
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Mount the Prometheus config
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"  # Grafana port
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Set admin password
    depends_on:
      - prometheus  # Ensure Prometheus starts before Grafana