global:
  scrape_interval: 3s  # How often to scrape targets

scrape_configs:
  - job_name: 'law-docs'  # Name of your application
    static_configs:
      - targets: ['host.docker.internal:8080']  # Adjust this to your application's metrics endpoint