// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/wilbyang/law-docs/models"
)

type Document struct {
	ID        int32
	Title     string
	Content   string
	DocSize   int32
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	Meta      models.Credentials
	Status    pgtype.Text
	AuthorID  pgtype.Int4
}

type User struct {
	ID        int32
	Name      string
	Email     string
	Password  string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
