// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/wilbyang/law-docs/models"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (
    title,
    content,
    doc_size,
    created_at,
    updated_at,
    meta
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
) RETURNING id, title, content, doc_size, created_at, updated_at, meta, status, author_id
`

type CreateDocumentParams struct {
	Title     string
	Content   string
	DocSize   int32
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	Meta      models.Credentials
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.Title,
		arg.Content,
		arg.DocSize,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Meta,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.DocSize,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Meta,
		&i.Status,
		&i.AuthorID,
	)
	return i, err
}
